spring:
  config:
    activate:
      on-profile: local
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    sender-name: ${MAIL_SENDER}