spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:boilerplate
    username: root
    password:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true


logging:
  file:
    path: logs
  level:
    com:
      boilerplate: debug
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
  logback:
    rolling policy:
      max-history: 7