spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver