spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      cookie:
        same-site: lax
        secure: false

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      cookie:
        same-site: lax
        secure: true

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      cookie:
        same-site: lax
        secure: true

---
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html