spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      enabled: true
      lifecycle-management: start-only
---
spring:
  config:
    activate:
      on-profile: dev
  docker:
    compose:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: prod
  docker:
    compose:
      enabled: false