spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
#          google:
#            client-id:
#            client-secret:
#            scope:
#              - profile
#              - email

          naver:
            client-id: H0JlkouFYrGG3L1ho2Yj
            client-secret: LZNC1i53lL
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

          kakao:
            client-id: a389cced6b32b6a02477b231e3772ba2
            client-secret: rgydHA812Xk0m737EeMVW1NGOZsGaKM0
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id



