logging:
  file:
    path: logs
  level:
    com.onoffmix: debug
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
  logback:
    rolling policy:
      max-history: 7
spring:
  config:
    activate:
      on-profile: local
---
logging:
  file:
    path: logs
  logback:
    rolling policy:
      max-history: 365
spring:
  config:
    activate:
      on-profile: dev
---
logging:
  file:
    path: logs
  logback:
    rolling policy:
      max-history: 365
spring:
  config:
    activate:
      on-profile: prod
---
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true